def all_parameters(run):
    log.info("Complete text input with ALL available parameters")
    log.info("")
    log.info("Configured parameters:")
    log.info("  - id: complete_text_input (unique identifier)")
    log.info("  - type: text (component type)")
    log.info("  - label: Device Identifier (display label)")
    log.info("  - placeholder: DEV-XXXX-YYYY-ZZZZ (hint text)")
    log.info("  - description: Detailed instructions for operator")
    log.info("  - required: true (must be filled)")
    log.info("  - value: DEV- (default/pre-filled value)")
    log.info("  - pattern: ^DEV-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$ (validation regex)")
    log.info("  - bind: measurement.device_identifier (save to measurement)")
    log.info("")
    log.info("This demonstrates all text input capabilities in one component")
